spring:
  datasource:
    diver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ToDoList?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: 123456

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mvc:
    validation:
      enabled: true
      locale: zh_TW
