spring:
  datasource:
    diver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ToDoList?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: 123456
    web:
      resources:
        static-locations: classpath:/static/
  mvc:
    validation:
      enabled: true
      locale: zh_TW
    static-path-pattern: /**

server:
  port: 8181